Add curly rule for statement after flow control clause
spoke-ph/eslint-config-spoke pull request #13
Opened 2022-05-31 04:25 UTC by linlin1023

2022-05-31 04:27 UTC, dekpient requested changes
this reminds me; we should add the sort import thingy as a dep @0608jennylee ?

2022-05-31 04:28 UTC, 0608jennylee commented
> yup I've asked @linlin1023 to add it as well

2022-05-31 04:31 UTC, cml35 commented on configs/common.js
> +    "simple-import-sort/imports": "error",
Do we want it as warn?

2022-05-31 04:44 UTC, linlin1023 commented on configs/common.js
> +    "simple-import-sort/imports": "error",
we want error correct me if I get it wrong @dekpient , so far all the forced rules are set to be error level

2022-05-31 04:48 UTC, 0608jennylee commented on configs/common.js
> +    "simple-import-sort/imports": "error",
It should be error, it should be changed to warn only for repos that we dont want to sort all the imports yet

2022-05-31 04:50 UTC, 0608jennylee approved these changes

2022-05-31 22:29 UTC, cojj90 submitted a review, later dismissed
lgtm

2022-06-01 22:17 UTC, cojj90 approved these changes

2022-06-01 22:43 UTC, dekpient approved these changes

2022-06-01 23:02 UTC, cojj90 approved these changes

2022-06-01 23:02 UTC, merged