Add ESLint rules around spacing and dangling commas
spoke-ph/eslint-config-spoke pull request #5
Opened 2020-10-03 06:48 UTC by dekpient

2020-10-04 19:58 UTC, dekpient commented on configs/common.js
> +    "comma-dangle": ["error", {
what do people think about this?

2020-10-04 20:00 UTC, cojj90 commented on configs/common.js
> +    "comma-dangle": ["error", {
I say "only-multilineI" -  like dangling commas on multi-line

2020-10-04 22:40 UTC, danieljimeneznz commented on configs/common.js
> +    "comma-dangle": ["error", {
My only comment on `always-multiline` is that I think most of our code currently follows `never` so the PR in the repo that updates this might be quite large

2020-10-05 02:39 UTC, dekpient commented on configs/common.js
> +    "comma-dangle": ["error", {
`only-multiline` means it's optional, i want to enforce dangling commas when you have things on multiple lines

2020-10-05 19:40 UTC, SimonRobinson requested changes

2020-10-05 19:40 UTC, SimonRobinson commented on configs/common.js
> +    "comma-dangle": ["error", {
https://eslint.org/docs/rules/comma-dangle lets talk with words

2020-10-05 21:02 UTC, danieljimeneznz approved these changes

2020-10-05 21:02 UTC, SimonRobinson approved these changes

2020-10-05 21:02 UTC, merged